name: fap_properties
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


#     /* Note */
#  // =====================>
#  // // For Production (Renew  and Offer Letter)
#  // =====================>
#  // // For Production (Leasing)
#  // =====================>
# // // remove +92 
# // // must correct the condition of the Appversion
# // For Production  Must uncomment before go live
# // Must check both places before going the live


version: 1.0.15+27
# version: 1.0.14+25
# version: 1.0.13+24
# version: 1.0.12+20
# version: 1.0.11+19
# version: 1.0.10+18
# version: 1.0.9+17
# version: 1.0.8+14
# version: 1.0.6+10
# version: 1.0.5+9
# version: 1.0.4+8
# version: 1.0.4+7
# version: 1.0.3+6
# version: 1.0.2+5
# version: 1.0.1+4
# version: 1.0.1+3

environment:
  sdk: ">=2.11.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

# in some packages we use any instead of package version because we were facing som issue in flutter pub ge
# this is temporary 
dependencies:
  animated_text_kit: ^4.2.1
  awesome_dialog: ^3.0.2
  badges: ^2.0.1
  carousel_slider: ^4.0.0
  clippy_flutter: ^1.1.1
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  countdown_progress_indicator: ^0.1.2
  cupertino_icons: ^1.0.2
  encrypted_shared_preferences: ^3.0.0
  extended_image: ^6.2.1
  firebase_auth: any
  firebase_core: any #^2.3.0
  firebase_app_check: any #^0.1.1+10
  firebase_messaging: any #^14.1.1
  flutter_html: any #^2.2.1
  flutter_image_compress: ^1.1.0
  flutter_jailbreak_detection: ^1.8.0
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.2
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_rounded_date_picker: ^3.0.2
  flutter_slidable: ^0.6.0
  flutter_swiper: ^1.1.6
  flutter_switch: ^0.3.2
  flutter_tab_indicator_styler: ^2.0.0
  flutter_windowmanager: ^0.2.0
  get: ^4.3.8
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.1
  apple_maps_flutter: ^1.2.0
  # google_mlkit_text_recognition: ^0.5.0
  google_mlkit_text_recognition: ^0.10.0
  http_proxy: ^1.2.0
  image: any #^3.2.0
  image_editor_plus: ^0.1.5
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  keyboard_actions: ^4.1.0
  local_auth: ^2.1.2
  marquee: ^2.2.3
  # open_file: ^3.2.1
  # file_picker: ^4.5.0
  file_picker: any
  open_file: ^3.3.1
  package_info: ^2.0.2
  permission_handler: any
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.3.0
  scrollable_positioned_list: any
  shape_of_view_null_safe: ^2.0.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  signature: ^5.0.0
  sizer: ^2.0.15
  smooth_star_rating: ^1.1.1
  ssl_pinning_plugin: ^2.0.0
  syncfusion_flutter_charts: ^20.3.58
  syncfusion_flutter_datepicker: ^20.3.58
  system_proxy: ^0.1.0
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.2
  video_player_web: ^2.0.12
  wakelock_web: ^0.4.0
  webviewx: ^0.2.1
  zoom_pinch_overlay: ^1.2.0
  flutter_dotenv: ^5.0.2
  encrypt: ^5.0.1
  crypto: ^3.0.2
  http_certificate_pinning: ^2.0.4
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.11
  # flutter_autoupdate: ^1.0.0 # ios
  in_app_update: ^4.0.1 # android
  flutter_multi_formatter: ^2.10.2
   # like 123-1234-1232312-3
  launch_review: ^3.0.1
  # simple_tooltip: ^1.2.0
  video_player: any
  photo_view: ^0.14.0

   # edge_detection: ^1.0.9
  # 
  # path: ^1.8.2
  # privacy_screen: ^0.0.6  # this package (when app is background show only spash screen instead of showing data)


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/common_images/app_icon/new_app_logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/common_images/
    - assets/images/tenant_images/
    - assets/images/landlord_images/
    - assets/images/tenant_images/tenant_dashboard/
    - assets/images/tenant_images/tenant_contracts/
    - assets/images/vendor_images/
    - assets/icons/
    - assets/images/public_images/
    - .env
    - assets/images/common_images/app_icon/appStore.png
    - assets/images/common_images/app_icon/playStore.png
    - assets/images/common_images/pdf.png
    - assets/video/FAB_8.mp4
    - assets/video/WithMunciplity.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GraphikRegular
      fonts:
        - asset: assets/fonts/GraphikRegular.ttf
    - family: GraphikSemibold
      fonts:
        - asset: assets/fonts/GraphikSemibold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
