#  /* Note */
#  // =====================>
#  // // For Production (Renew  and Offer Letter)
#  // =====================>
#  // // For Production (Leasing)
#  // =====================>
# // // remove +92
# Must check both places before going the live

name: fap_properties
description: A new Flutter project.
publish_to: "none"
version: 1.0.14+26

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.5
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.2.1
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  countdown_progress_indicator: ^0.1.3
  cupertino_icons: ^1.0.8
  encrypted_shared_preferences: ^3.0.1
  extended_image: ^8.2.1
  firebase_core: ^2.15.0 # firebase_core: ^2.15.0
  firebase_auth: ^4.1.0 # firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.0 # firebase_messaging: any #^15.1.0 # firebase_messaging: ^14.0.0
  firebase_app_check: ^0.2.1+8 # firebase_app_check: ^0.2.1+8
  flutter_image_compress: ^2.3.0
  flutter_jailbreak_detection: ^1.10.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  flutter_pdfview: ^1.3.2
  flutter_phoenix: ^1.1.1
  flutter_rating_bar: ^4.0.1
  flutter_rounded_date_picker: ^3.0.4
  # flutter_swiper: ^1.1.6
  flutter_swiper_view: ^1.1.8
  flutter_switch: ^0.3.2
  flutter_tab_indicator_styler: ^2.0.0
  flutter_windowmanager: ^0.2.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0 # creating issue while creating build
  apple_maps_flutter: ^1.3.0 # creating issue //
  google_mlkit_text_recognition: ^0.13.0
  http_proxy: ^1.2.2
  image: ^4.2.0 # if create any issue the will use 4.0.7
  image_editor_plus: any #^1.0.6 #^1.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  keyboard_actions: ^4.2.0
  local_auth: ^2.3.0
  marquee: ^2.2.3
  sizer: ^3.0.3
  flutter_lints: ^4.0.0
  flutter_slidable: ^3.1.1
  firebase_messaging_web: ^3.8.7 # 3.8.11
  file_picker: ^8.1.2
  open_file: ^3.5.0+1
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  scrollable_positioned_list: any #^0.3.8
  shape_of_view_null_safe: ^3.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  signature: ^5.5.0
  
  smooth_star_rating_null_safety: ^1.0.4+2
  syncfusion_flutter_charts: ^26.2.11
  syncfusion_flutter_datepicker: ^26.2.11
  syncfusion_flutter_core: ^26.2.11
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.0
  video_player_web_hls: ^1.3.0
  zoom_pinch_overlay: ^1.4.3
  flutter_dotenv: ^5.1.0
  encrypt: ^5.0.3
  # crypto: ^3.0.5
  http_certificate_pinning: ^2.1.3
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.4
  in_app_update: ^4.2.3
  flutter_multi_formatter: ^2.13.0
  video_player: ^2.9.1
  path: ^1.9.0
  http: ^1.2.2
  firebase_core_web: ^2.17.5
  fluttertoast: ^8.2.8
  image_picker_for_web: ^3.0.5
  photo_view: ^0.15.0
  launch_review: any
  webviewx: ^0.1.0 # using downgrade version but it support null safety acctually have conflict with http if i increase it version
  wakelock_plus: ^1.2.8
  system_proxy: ^0.1.0
  flutter_html: ^3.0.0-beta.2
 
  flutter_localizations:
    sdk: flutter

 
dependency_overrides:
  # ssl_pinning_plugin: any
  # ssl_pinning_plugin: ^2.0.0
  sizer: ^2.0.15 # i can not update this because our main func is disturbinf from this
  # image: ^3.0.1 # any #^3.2.0 i can not update this because our main func is disturbinf from this
  # flutter_slidable: ^0.6.0 # i can not update this because our main func is disturbing from this
  web: ^0.5.1 # it not useable in project i added this for getting rid of conflict b/w file_picker & firebase_messaging_web
  url_launcher_web: any 
  fading_edge_scrollview: ^4.1.1
  
  # not available on pub dev that is why i put in override
  # syncfusion_flutter_charts:
  #   git:
  #     url: https://github.com/Luvti/flutter-widgets
  #     path: packages/syncfusion_flutter_charts
  #     ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/common_images/app_icon/new_app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/common_images/
    - assets/images/tenant_images/
    - assets/images/landlord_images/
    - assets/images/tenant_images/tenant_dashboard/
    - assets/images/tenant_images/tenant_contracts/
    - assets/images/vendor_images/
    - assets/icons/
    - assets/images/public_images/
    - .env
    - assets/images/common_images/app_icon/appStore.png
    - assets/images/common_images/app_icon/playStore.png
    - assets/images/common_images/pdf.png
    - assets/video/FAB_8.mp4
    - assets/video/WithMunciplity.mp4

  fonts:
    - family: GraphikRegular
      fonts:
        - asset: assets/fonts/GraphikRegular.ttf
    - family: GraphikSemibold
      fonts:
        - asset: assets/fonts/GraphikSemibold.ttf
