// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwNDuTYZNGUYAwhDj1Zt2QZf7EEi8G0o',
    appId: '1:437162741952:web:4efb4e3b664fa9e22c5d25',
    messagingSenderId: '437162741952',
    projectId: 'fab-properties',
    authDomain: 'fab-properties.firebaseapp.com',
    storageBucket: 'fab-properties.appspot.com',
    measurementId: 'G-XS3222XDCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLBm86W5MY_ZVZ0Ts8qPOmn7ioXOfCfvE',
    appId: '1:437162741952:android:c4f606634e6e28442c5d25',
    messagingSenderId: '437162741952',
    projectId: 'fab-properties',
    storageBucket: 'fab-properties.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTd7ZT_TpIeAhGBW-nWmkap94cNetiPg',
    appId: '1:437162741952:ios:824ccdd9fff2c81a2c5d25',
    messagingSenderId: '437162741952',
    projectId: 'fab-properties',
    storageBucket: 'fab-properties.appspot.com',
    iosClientId: '437162741952-odcqv6729gammingrlehl3unumkmrnsj.apps.googleusercontent.com',
    iosBundleId: 'com.fab',
  );
}
