# org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096M
oorg.gradle.parallel=true
kotlin.jvm.target.validation.mode = IGNORE
org.gradle.configureondemand=true
kotlin.incremental=true
org.gradle.jvmargs=-Dhttps.protocols=TLSv1.2,TLSv1.3 -DsystemProp.ssl.KeyManagerFactory.algorithm=SunX509


